#!/usr/bin/env bash
#
# This script installs git configurations.
#
# This script uses 'utils.sh', my custom library for manager dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.com>. All
# right reserved. This file is license under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

ed_exists "xdg-user-dir"
ed_exists "readlink"

dest_dir="$(xdg-user-dir)"

ed_make_symlink "$(readlink -f gitconfig)" "$dest_dir/.gitconfig"
ed_make_symlink "$(readlink -f gitignore)" "$dest_dir/.gitignore"
