image: fedora:30

before_script:
  # Install 'find' and 'shellcheck' command.
  - dnf --quiet --assumeyes install ShellCheck findutils

lint-bash:
  stage: test
  # Find all Bash script and lint them, but exclude 'test.sh', that is a Bash
  # script of a git submodule.
  # Disable also SC1091, it is a warning for files not checked in Bash 'source'.
  script: 'find . -not -name "test.sh" -and -name "*.sh" -or -name "install" -exec shellcheck --color=always --exclude=SC1091 {} \;'
