image: fedora:30

before_script:
  - cat /os/release
  - dnf --version
  - dnf --assumeyes install ShellCheck findutils make

lint-bash-module:
  stage: test
  script: make lint-bash-module

lint-bash-dotfiles:
  stage: test
  script: make lint-bash-dotfiles

lint-bash-bin:
  stage: test
  script: make lint-bash-bin
