image: fedora:30

before_script:
  - cat /etc/os-release
  - dnf --version
  - dnf --assumeyes install ShellCheck findutils make python3-flake8

lint:
  stage: test
  script: make --jobs $(nproc) lint
