#!/usr/bin/env bash
#
# This script manages my dotfiles. Run `dotfiles help' to get more informations.
#
# Copyright (c) 2018-2019 Emanuele Petriglia <inbox@emanuelepetriglia.com>
# All rights reserved. This file is licensed under the MIT license.

# This file id divided into several sections:
#   - List of global variables;
#   - List of common used functions;
#   - List of various modules (a script that does something);
#   - List of commands;
#   - Script's entry point.

# Global variables {{{

set -e

# Useful to display a prefix on logging messages.
CURRENT_MODULE=""

# Full path of dotfiles repository.
readonly REPO_PATH="$(dirname "$(readlink -f "$0")")"

# Full path of user's home dir.
readonly HOME_PATH="$(xdg-user-dir)"

# Program's name.
readonly PROGRAM="${0##*/}"

# User given command.
readonly COMMAND="$1"

# Target of this script.
readonly TARGET_DISTRIBUTION="Fedora"
readonly TARGET_VERSION=31

# Associative array of available modules (module name -> module description).
declare -A MODULES

# Default exit codes.
readonly EXIT_SUCCESS=0
readonly EXIT_FAILURE=1

# }}}

# Common used functions {{{

# Logging {{{{

# Prints a message to the standard output. If 'CURRENT_MODULE' is not empty, it
# uses the value as prefix.
#
# Parameter:
#     $1 -> the message to print to the standard output.
#
# Example:
#     $ CURRENT_MODULE="test" ed_log "Some application downloaded!"
#     test: Some application downloaded!
#
ed_log() {
  if [[ "$CURRENT_MODULE" ]]; then
    echo -n "$CURRENT_MODULE: "
  fi

  echo "$1"
}

# Prints a message to the standard error. If 'CURRENT_MODULE' is not empty, it
# uses the value as prefix.
#
# Parameter:
#     $1 -> the message to print to the standard error.
#
# Example:
#     $ CURRENT_MODULE="test" ed_wlog "Skipping some tasks!"
#     test: Skipping some tasks!
#
ed_wlog() {
  ed_log "$1" >&2
}

# It prints a message to the standard error and exits with an error code. If
# 'CURRENT_MODULE' is not empty, it uses the value as prefix.
#
# Parameters:
#     $1 -> the message to print to the standard error;
#     $2 -> the error code, default is $EXIT_FAILURE (optional);
#     $3 -> an optional function or command to run before exit (optional).
#
# Example:
#     $ CURRENT_MODULE="test" ed_elog "X not found!" 5
#     test: X not found
#     $ echo $?
#     5
#     $ ed_elog "failed to do..." 1 "echo ciao"
#     failed to do...
#     ciao
#
ed_elog() {
  ed_wlog "$1"

  [[ "$3" ]] && "$3" # Run a command before exiting, if exists.

  exit "${2:-$EXIT_FAILURE}" # If $2 is unset or empty, set to default.
}

# }}}}

# DNF / RPM {{{{

# It installs the given packages via DNF.
#
# Parameters:
#     $1 ... $n -> a list of packages to install.
#
# Example:
#     ed_install "pass" "thunderbird" "vlc" "youtube-dl" "telegram-desktop"
ed_install() {
  if (( $# < 1 )); then
    ed_elog "No given package to install."
  fi

  # Remove installed packages from the list.
  declare -A packages
  for package in "$@" ; do
    if ! rpm --quiet --query "$package"; then
      packages["$package"]=""
    fi
  done

  # Install only missing packages (some packages may not exist).
  if (( ${#packages[@]} != 0 )); then
    ed_wlog "root requested to install these packages: ${!packages[*]}"
    sudo dnf install "${!packages[@]}"
  fi
}

# }}}}

# Filesystem commons {{{{

# It creates a simlink of a directory or file.
#
# Parameters:
#     $1 -> source path (a file or a directory);
#     $2 -> destination path;
#     $3 -> if 'sudo' it creates a symlink using root permissions.
#
# Example:
#     ed_make_symlink path/to/source path/to/dst
ed_make_symlink() {
  local src="$1"
  local dst="$2"

  if [[ "$3" == "sudo" ]]; then
    local sudo="sudo"
  fi

  if [[ -z "$src" ]]; then
    ed_elog "Error: source path is empty"
  fi

  if [[ -z "$dst" ]]; then
    ed_elog "Error: destination path is empty"
  fi

  if [[ -L "$dst" ]]; then
    local real_dst_path
    real_dst_path="$(readlink -f "$dst")"

    if [[ "$real_dst_path" != "$src" ]]; then
      ed_elog "Error: $dst is a symlink to $real_dst_path, not to $src"
    else
      ed_log "$dst is already a symlink to $src"
    fi
  else
    if [[ "$sudo" ]]; then
      ed_wlog "root required to create symlink \"$src\" -> \"$dst\""
    fi

    $sudo ln --symbolic --force --verbose "$src" "$dst"
  fi
}

# }}}}

# It is a wrapper to 'curl', to download files to some point. If there is a
# problem, it will don't exit, instead it returns 1 (0 is success).
#
# Parameters:
#   $1 -> file to download;
#   $2 -> path and name to save the downloaded file
#
# Example:
#   ed_download "http://example.com/" "$HOME/Downloads/example.com"
ed_download() {
  local src="$1"
  local dst="$2"

  # '--location' is needed to follow redirects.
  curl --location --silent --show-error "$src" --output "$dst" || return 1

  return 0
}

# Wrapper to 'xfconf-query'. It checks channel, property and value before run
# 'xfconf-query'. It also avoid useless rewrite.
#
# Parameters:
#   $1 -> channel;
#   $2 -> Property;
#   $3 -> Value (string).
#
# Example:
#   ed_xfconf "xsettings" "/Net/IconThemeName" "Papirus-Dark"
ed_xfconf() {
  [[ ! "$1" || ! "$2" || ! "$3" ]] && ed_elog "Missing arguments for ed_xfconf"
  local channel="$1"
  local property="$2"
  local value="$3"

  local current
  if ! current="$(xfconf-query --channel "$channel" --property "$property" 2>&1)"
  then
    ed_elog "xfconf-query: $current"
  fi

  if [[ "$current" == "$value" ]]; then
      ed_wlog "xfconf-query: $value for $channel$property is already set!"
    else
      xfconf-query --channel "$channel" --property "$property" --set "$value"
  fi
}

# }}}

# Modules {{{

MODULES["packages"]="install various packages"
ed_module_packages() {
  local repository
  repository="https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm"

  # Install RPM Fusion (free) repository.
  if [[ -f "/etc/yum.repos.d/rpmfusion-free.repo" ]]; then
    ed_wlog "RPM Fusion free repository is already added!"
  else
    ed_wlog "root requested to install RPM Fusion free repository"
    sudo dnf install "$repository"
  fi

  ed_install "pass" "thunderbird" "vlc" "youtube-dl" "telegram-desktop"
}

MODULES["gtk"]="enable Arc-Dark GTK+ theme"
ed_module_gtk() {
  ed_xfconf "xsettings" "/Net/ThemeName" "Arc-Dark"
}

MODULES["icon"]="install 'papirus-icon-theme' package and enable it"
ed_module_icon() {
  ed_install "papirus-icon-theme"

  ed_xfconf "xsettings" "/Net/IconThemeName" "Papirus-Dark"
}

MODULES["bin"]="create symlinks for custom scripts on ~/.local/bin"
ed_module_bin() {
  local bin_path="$HOME_PATH/.local/bin"

  mkdir --parents "$bin_path"

  for script in "$REPO_PATH"/bin/* ; do
    ed_make_symlink "$script" "$bin_path/${script##*/}"
  done
}

MODULES["git"]="install 'git' and link the configuration"
ed_module_git() {
  local dest_path="$HOME_PATH"

  ed_install "git"

  mkdir --parents "$dest_path"

  for config in "$REPO_PATH"/git/* ; do
    # Because git config are dotfiles, they starts with '.'.
    ed_make_symlink "$config" "$dest_path/.${config##*/}"
  done
}

MODULES["tlp"]="install 'tlp', link the configuration and enable it"
ed_module_tlp() {
  local src dst

  ed_install "tlp"

  # Create symlink (with backup).
  src="$REPO_PATH/tlp/tlp"
  dst="/etc/default/tlp"

  if [[ "$(readlink -f "$dst")" != "$src" ]] ; then
    sudo ln --backup --suffix '.bak' --symbolic "$src" "$dst"
  else
    ed_wlog "'$dst' is already a symlink to '$src'."
  fi

  # Before enabling tlp, you need to fix a SELinux policy.
  local policy="$REPO_PATH/tlp/fix-tlp"
  checkmodule --mls -m -o "$policy.mod" "$policy.te"
  semodule_package -o "$policy.pp" -m "$policy.mod"

  ed_wlog "root requested to install '$policy.te' policy!"
  sudo semodule --install "$policy.pp"
  ed_log "policy installed successfuly!"

  rm --force "$policy.pp" "$policy.mod"

  # Enable tlp
  ed_wlog "root requested to start tlp!"
  sudo tlp start &>>/dev/null || ed_elog "tlp: Failed to start tlp!"
  ed_log "tlp started successfuly!"
}

MODULES["dotfiles"]="install itself to '~/.local/bin'"
ed_module_dotfiles() {
  ed_make_symlink "$REPO_PATH/$PROGRAM" "$HOME_PATH/.local/bin/$PROGRAM"
}

MODULES["clean"]="remove various packages that I don't use"
ed_module_clean() {
  sudo dnf remove "gnome-keyring" "seahorse" "xfdashboard" "claws-mail" \
                  "xscreensaver-base" "xfburn" "geany" "pidgin" "asunder" \
                  "pragha" "parole" "dnfdragora" "gnumeric" \
                  "xfce4-dict" "orage" "xfce4-clipman-plugin" \
                  "firewall-config" "cups" "catfish"

}

MODULES["gpg"]="install GnuPG configuration and enable it via systemd --user"
ed_module_gpg() {
  # 1. Install my favourite pinentry.
  ed_install "pinentry-gtk"

  # 2. Create symlinks for configuration.
  for file in "$REPO_PATH"/gnupg/* ; do
    ed_make_symlink "$file" "$HOME_PATH/.gnupg/${file##*/}"
  done

  local dest_unit="$HOME_PATH/.config/systemd/user"
  local src_unit="/usr/share/doc/gnupg2/examples/systemd-user"

  # 3. Create symlinks for systemd unit files.
  mkdir --parents "$dest_unit"
  for unit in "$src_unit"/*.{service,socket} ; do
    ed_make_symlink "$unit" "$dest_unit/${unit##*/}"
  done

  # 4. Enable systemd unit files.
  systemctl --user daemon-reload

  local socket
  for full_socket in "$src_unit"/*.socket ; do
    socket="${full_socket##*/}"

    systemctl --user enable "$socket"
    systemctl --user start "$socket"
  done
}

MODULES["lightdm"]="link LightDM configuration"
ed_module_lightdm() {
  ed_make_symlink "$REPO_PATH/lightdm/lightdm.conf" \
                  "/usr/share/lightdm/lightdm.conf.d/70_start_xfce_session.conf"\
                  sudo
}

MODULES["vim"]="prepare vim folder and link it to $HOME_PATH/.vim"
ed_module_vim() {
  local plugins_path

  ed_make_symlink "$REPO_PATH/vim" "$HOME_PATH/.vim"

  plugins_path="$REPO_PATH/vim/pack/plugins/start/"

  # Download all plugins.
  git -C "$REPO_PATH" submodule update --init "$plugins_path/papercolor-theme"
  git -C "$REPO_PATH" submodule update --init "$plugins_path/vim-syntax-extra"
  git -C "$REPO_PATH" submodule update --init "$plugins_path/python-syntax"
  git -C "$REPO_PATH" submodule update --init "$plugins_path/goyo.vim"
  git -C "$REPO_PATH" submodule update --init "$plugins_path/vim-pencil"
}

MODULES["xfce4"]="link configuration of various Xfce apps"
ed_module_xfce4() {
  local dest_path src_path

  dest_path="$HOME_PATH/.config/xfce4/terminal"
  src_path="$REPO_PATH/xfce4/xfce4-terminal"

  ed_make_symlink "$src_path/terminalrc" "$dest_path"
  ed_make_symlink "$src_path/colorschemes" "$dest_path"

  # I use 'xfce4-panel-profiles' to make backup and restore my 'xfce4-panel'
  # configuration. This program accepts only a tar file that contains the
  # configuration.
  local tar_conf

  tar_conf="$(mktemp --suffix='.tar')"

  tar -cf "$tar_conf" --directory "$REPO_PATH/xfce4/xfce4-panel" "config.txt"

  ed_log "Loading xfce4-panel configuration..."
  xfce4-panel-profiles load "$tar_conf"

  rm --force "$tar_conf"
}

MODULES["thunar"]="install Thunar configuration"
ed_module_thunar() {
  local channel="thunar"

  ed_wlog "note that if you change Thunar config from GUI, the new configuration
  is not updated on dotfiles. You need to update manually!"

  # Show hidden files (starting with a dot).
  ed_xfconf "$channel" "/last-show-hidden" "true"

  # Icon zoom level.
  ed_xfconf "$channel" "/last-icon-view-zoom-level" \
    "THUNAR_ZOOM_LEVEL_150_PERCENT"
}

MODULES["xfwm4"]="install xfwm4 theme"
ed_module_xfwm4() {
  local dest_path

  dest_path="$HOME_PATH/.local/share/themes"
  mkdir --parents "$dest_path"

  ed_make_symlink "$REPO_PATH/xfwm4/thinble" "$dest_path/thinble"
}

MODULES["bash"]="link Bash configuration"
ed_module_bash() {
  for file in "$REPO_PATH"/bash/* ; do
    ed_make_symlink "$file" "$HOME_PATH/.${file##*/}"
  done
}

MODULES["font"]="download and install Hack font (but don't activate it)"
ed_module_font() {
  local xz_file
  local tar_file
  local dest_path="$HOME_PATH/.local/share/fonts"
  local hack_version="v3.003"

  xz_file="$(mktemp --suffix=.tar.xz)"
  tar_file="${xz_file%%.xz}"

  local hack_dl_file="Hack-$hack_version-ttf.tar.xz"
  local hack_dl_url="https://github.com/source-foundry/Hack/releases/download/$hack_version/$hack_dl_file"

  # Download the font files.
  ed_download "$hack_dl_url" "$xz_file" ||
    ed_elog "Failed to download '$hack_dl_url'" "$EXIT_FAILURE" "rf --force $xz_file"

  # Extract the pack and install the fonts.
  xz --decompress "$xz_file" ||
    ed_elog "Failed to decompress '$xz_file'" "$EXIT_FAILURE" "rf --force $xz_file"

  mkdir --parents "$dest_path"

  tar --extract --file "$tar_file" --directory "$dest_path" ||
    ed_elog "Failed to extract '$tar_file'" "$EXIT_FAILURE" "rf --force $tar_file"

  rm --force "$tar_file" # Remove downloaded file.

  ed_log "clearing and rigenerating font cache, it may taking a while..."
  fc-cache --verbose --force "$dest_path"
}

MODULES["firefox"]="install firefox and custom user.js to 'emanuele' profile"
ed_module_firefox() {
  ed_install "firefox"

  local firefox_path="$HOME_PATH/.mozilla/firefox"

  # Find profile path.
  [[ -d "$firefox_path" ]] ||
    ed_elog "No '$firefox_path' folder found. Is Firefox installed?"

  local profile_path
  profile_path="$(find "$firefox_path" -maxdepth 1 -regex '.*\.default-release$')"

  [[ "$profile_path" ]] ||
    ed_elog "No profile with suffix 'default-release' found!"

  # Download and install custom user.js.
  local ghacks_js_url="https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/user.js"
  local dest_user_js="$profile_path/user.js"
  local custom_user_js="$REPO_PATH/firefox/user.js"

  ed_download "$ghacks_js_url" "$dest_user_js" ||
    ed_elog "Failed to download '$ghacks_js_url'"

  cat "$custom_user_js" >> "$dest_user_js" # Note: append, don't overwrite!
}

# }}}

# Command line interface {{{

# It prints to the standard output an help message with usage instructions.
ed_cmd_help() {
  cat <<-_EOF
Usage:
    $PROGRAM [ COMMAND ] [ ARGS ] ...

  This script manages my custom dotfiles. My dotfiles are organized as
  "modules". A module is simply a Bash script, it can install packages (via DNF)
  or create symlinks for the configuration.

Commands:
    list
        List all available modules.

    install <module>...
        Install the given modules. If the first given module is 'all', it
        installs all modules.

    help
        Show this text.

    version
        Show version information.

Example:

    The following command install the "telegram" module:
    $ $PROGRAM install telegram

Files:

    $REPO_PATH
        Dotfiles repository.

_EOF
}

# It prints to the standard output a list of available modules.
ed_cmd_list() {
  local sorted_modules

  ed_log "${#MODULES[*]} available modules:"

  # Formatting like this: module name     - module description
  sorted_modules="$(echo "${!MODULES[*]}" | tr " " "\n" | sort | tr "\n" " ")"
  for module in $sorted_modules ; do
    printf "%-13s - %s\n" "$module" "${MODULES["$module"]}"
  done
}

# It installs all modules given as input.
ed_cmd_install() {
  local nr_modules
  [[ "$1" ]] || ed_elog "No modules given."

  # 'all' is a special module, it installs all modules.
  if [[ "$1" == "all" ]]; then
    set -- "${!MODULES[@]}"
  fi

  # Check if exist given modules.
  for module in "$@" ; do
    [[ "${MODULES["$module"]}" ]] || ed_elog "Module '$module' doesn't exist."
  done

  nr_modules="$#"
  ed_log "Installing $nr_modules modules..."

  while [[ "$1" ]]; do
    # Note that '$#' change every iteration, because of 'shift'. It is a counter
    # like this: (4/7) Installing module foo...
    ed_log "($((nr_modules - $# + 1))/$nr_modules) Installing module $1..."

    # The module name is also the suffix of the function.
    CURRENT_MODULE="$1" ed_module_"$1"

    shift
  done
}

# }}}

# Entry point {{{

# Check operating system name and version.
if [[ -e "/etc/os-release" ]]; then
  source "/etc/os-release"
elif [[ -e "/etc/usr/lib/os-release" ]]; then
  source "/etc/usr/lib/os-release"
else
  ed_elog "Failed to establish the current operating system name and version"
fi

if [[ "$NAME" != "$TARGET_DISTRIBUTION" || "$VERSION_ID" != "$TARGET_VERSION" ]]; then
  ed_wlog "Host OS is $NAME $VERSION_ID but this script is written for $TARGET_DISTRIBUTION $TARGET_VERSION. It might not work!"
fi

case "$COMMAND" in
  list) shift;              ed_cmd_list "$@" ;;
  install) shift;           ed_cmd_install "$@" ;;
  help|-h|--help) shift;    ed_cmd_help "$@" ;;
  version|--version) shift; echo "$PROGRAM script for $VERSION" ;;
  *) shift;                 ed_cmd_help "$@" ;;
esac

exit 0

# }}}

# vim:foldmethod=marker
