#!/usr/bin/env bash

# GENERAL
# ------------------------------------------------------------------------------

# Full path of the script.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# User directory.
# TODO: change the name.
USER="$(xdg-user-dir)"

# Useful tools used in this script.
LN="ln --force --interactive --symbolic"
MKDIR="mkdir --parents"
CP="cp --recursive"
RM="rm --recursive --force"

# Downlod all GIT submodules. It consists of the icon pack (Papirus), GTK theme
# and some VIM plugins.
git submodule update --init

# GTK+ Theme
# ------------------------------------------------------------------------------

# Download GTK+ theme.
TMPDIR="$(mktemp --directory)"
cd "$TMPDIR"

wget --content-disposition \
     --quiet \
     https://www.archlinux.org/packages/community/any/adapta-gtk-theme/download/

FILE="$(ls)"
xz --decompress "$FILE"

FILE="$(ls)"
tar xvf "$FILE" 1>/dev/null 2>/dev/null

sudo $CP usr/share/themes/Adapta /usr/share/themes/Adapta
sudo $CP usr/share/themes/Adapta-Nokto /usr/share/themes/Adapta-Nokto

cd $DIR

$RM $TMPDIR

# Note: the theme is not enabled here, only downloated and prepared. See
# xfce4 settings!

# XFCE
# ------------------------------------------------------------------------------

XFCONF="xfconf-query --create"

# Xfwm4
# ------------------------------------------------------------------------------

XFCONF_XFWM4="$XFCONF --channel xfwm4"

# Appling theme.
$XFCONF_XFWM4 -p /general/theme -t string -s borderless

# Use six workspaces.
$XFCONF_XFWM4 -p /general/workspace_count -t int -s 6

# Rename the workspaces
$XFCONF_XFWM4 -p /general/workspace_names -p /general/workspace_names \
    -t string -t string -t string -t string -t string -t string \
    -s A -s B -s C -s D -s E -s F

# Don't switch workspace if I'm moving the active window near the borders.
$XFCONF_XFWM4 -p /general/wrap_windows -t bool -s false

# Xfce4 keyboard shortcuts
# ------------------------------------------------------------------------------

XFCONF_KS="$XFCONF --channel xfce4-keyboard-shortcuts"

# Xfwm4 shortcuts
# ---------------

XFCONF_XFWM4_KS="$XFCONF_KS --property /xfwm4/custom/"

# Allow to close active window with <Alt>F1
$XFCONF_XFWM4_KS\<Alt\>F1 -t string -s close_window_key

# Allow to maximize active window with <Alt>F2
$XFCONF_XFWM4_KS\<Alt\>F2 -t string -s maximize_window_key

# Allow to move the active window with <Alt>F3
$XFCONF_XFWM4_KS\<Alt\>F3 -t string -s move_window_key

# Allow to resize the active window with <Alt>F4
$XFCONF_XFWM4_KS\<Alt\>F4 -t string -s resize_window_key


# Resize the active window on top.
$XFCONF_XFWM4_KS\<Primary\>\<Alt\>w -t string -s tile_up_key

# Resize the active window on left.
$XFCONF_XFWM4_KS\<Primary\>\<Alt\>a -t string -s tile_left_key

# Resize the active window on bottom.
$XFCONF_XFWM4_KS\<Primary\>\<Alt\>s -t string -s tile_down_key

# Resize the active window on right.
$XFCONF_XFWM4_KS\<Primary\>\<Alt\>d -t string -s tile_right_key


# Move to the previous (left) workspace.
$XFCONF_XFWM4_KS\<Primary\>\<Alt\>h -t string -s prev_workspace_key

# Move to the next (right) workspace.
$XFCONF_XFWM4_KS\<Primary\>\<Alt\>l -t string -s next_workspace_key

# Move the active window to the previous (left) workspace.
$XFCONF_XFWM4_KS\<Primary\>\<Shift\>\<Alt\>h  \
                                     -t string -s move_window_prev_workspace_key

# Move the active window to the next (right) workspace.
$XFCONF_XFWM4_KS\<Primary\>\<Shift\>\<Alt\>l  \
                                     -t string -s move_window_next_workspace_key


# Switch to the next window. (Default value)
# $XFCONF_XFWM4_KS\\<Alt\>Tab -t string -s cycle_windows_key

# Switch to the previous window.
$XFCONF_XFWM4_KS\<Primary\>\<Alt\>Tab -t string -s cycle_reverse_windows_key

# Xfce4 desktop
# ------------------------------------------------------------------------------

XFCONF_DESKTOP="$XFCONF --channel xfce4-desktop"

# Set current background.
$XFCONF_DESKTOP -p /backdrop/screen0/monitor0/workspace0/last-image \
                -t string -s $DIR/backgrounds/current.jpg

# Disable icons on desktop.
$XFCONF_DESKTOP -p /desktop-icons/style -t int -s 0


# Xfce4 notify
# ------------------------------------------------------------------------------

XFCONF_NOTIFY="$XFCONF --channel xfce4-notifyd"

# Use the correct theme.
$XFCONF_NOTIFY -p /theme -t string -s Adapta

# Set the right opacity.
$XFCONF_NOTIFY -p /initial-opacity -t float -s 0.85


# Xfce4 Power Manager.
# ------------------------------------------------------------------------------

XFCONF_PM="$XFCONF --channel xfc4-power-manager"

# TODO

# Xfce4 xsettings (general settings).
# ------------------------------------------------------------------------------

XFCONF_XS="$XFCONF --channel xsettings"

# Enable GTK theme.
$XFCONF_XS -p /Net/ThemeName -t string -s Adapta-Nokto

# Enable icon theme.
$XFCONF_XS -p /Net/IconThemeName -t string -s papirus-adapta-nokto
