= ema-pe dotfiles
Emanuele Petriglia
:toc:

== What they are

This repository contains some dotfiles, scripts and configurations that I use
everyday.

== Requirements

My dotfiles are distro-agnostic, but `dotfiles` script is written specifically
to work with **Fedora**. Custom scripts under `bin` are written to work with any
computer with Bash, also the configuration files of several programs.

== Installation

=== Dotfiles installation

My dotfiles are organized as modules. Every module is a small Bash script that
can do many things, usually they:

* Install software (via `dnf`);
* Install configuration files;
* Activate something (like services).

For a list of available modules run `dotfiles list`. Some modules have a
reserved folder, which contains specific configuration files.

=== Repository installation

You can directly download this repository and run the `dotfiles` script:

 $ git clone git@gitlab.com:ema-pe/dotfiles.git ~/.dotfiles

Or, if you don't have SSH keys installed:

----
$ git clone https://gitlab.com/ema-pe/dotfiles.git ~/.dotfiles
$ cd ~/.dotfiles
$ ./dotfiles install gpg git
$ # install gpg keys...
$ git remote set-url origin git@gitlab.com:ema-pe/dotfiles.git
----

== Modules

=== bash

This modules simply link my bash configuration, that consists of a `bashrc` and
`bash_profile` file. It contains essential environment variables, aliases and
small scripts.

'''

=== bin

This module links all custom scripts to `~/.local/bin`. These scripts are:

* link:bin/backup[*backup*]: this script syncs some data from my laptop to my
  external HDD.
* link:bin/firefox-tmp[*firefox-tmp*]: this script launchs a temporary Mozilla
  Firefox instance (useful for testing or debugging).
* link:bin/gandi-aliases[*gandi-aliases*]: this script manages aliases for my
  email hosted on https://www.gandi.net/en[Gandi.net].
* link:bin/goodmorningitalia[*goodmorningitalia*]: this script automatically
  subscribe a 30-days free trial on
  https://app.goodmorningitalia.it/[*goodmorningitalia.it*], an italian
  newsletter.
* link:bin/keyboard-shortcuts-help[*keyboard-shortcuts-help*]: this script shows
  a window with all my keyboard shortcuts.
* link:bin/sapienza-wifi[*sapienza-wifi*]: this script automatically logins to the
  Sapienza's WiFi network, without open a broswer.
* link:bin/screen-off[*screen-off*]: this simple script turns off the screen.

These script can be installed manually, each requires some software specificated
on the first lines (for example `jq` for link:bin/gandi-aliases[gandi-aliases]).

WARNING: Make sure that `~/.local/bin` has ben added to `PATH` if you run this
module!

'''

=== vim

I use VIM as my text editor for programming and writing. I found it very
productive and efficent.

My link:vim/vimrc[vimrc] file is well documented, i also use some plugins:

* https://github.com/junegunn/goyo.vim[*goyo.vim*]: for writing without
  distractions.
* https://github.com/NLKNguyen/papercolor-theme[*papercolor-theme*]: a VIM color
  scheme inspired by Google's Material Design.
* https://github.com/hdima/python-syntax[*python-syntax*]: better Python syntax
  highlighting.
* https://github.com/reedes/vim-pencil[*vim-pencil*]: better movements for
  writing prose.
* https://github.com/justinmk/vim-syntax-extra[*vim-syntax-extra*]: better C
  syntax highlighting.

Both *goyo.vim* and *vim-pencil* are not automatically started with VIM, instead
you need to run `vim -c Writing`.

'''

=== tlp

TLP is an useful package to manage power and extends battery life. It works well
with other power management software (like `xfce4-powermanager`).

The package can be found via Fedora official repository with the name `tlp`.

The default configuration file, located on `/etc/default/tlp` is good, but I've
done some customization (I'm using a Thinkpad laptop).

The basic commands available are:

* Start tlp: `sudo tlp start` (but there is also a unit file for systemd);
* Check the configuration: `sudo tlp stat`;
* Manage WiFi and Blueooth: `wifi [on/off]` and `bluetooth [on/off]`.

This module will install tlp, copy my configuration, start tlp and enable the
unit file (for systemd).

'''

=== dotfiles

This module installs the `dotfiles` script to `~/.local/bin` folder. It is
supposed that this path is added previously to `PATH` environment variable.

'''

=== clean

This module simply removes via `dnf` all preinstalled Fedora packaged that I
don't use. For a list of these packages, open the script and go to the `clean`
module.

'''

=== gpg

I use GnuPG to manager my PGP keys. GnuPG have also an agent called
`gpg-agent`, I use it also for SSH support. There is some configuration because
out-of-the-box Fedora uses `ssh-agent` and `gnome-keyring`.

The GnuPG file configuration is located at `~/.gnupg/gpg.conf`, the agent
configuration is located at `~/.gnupg/gpg-agent.conf`. This module installs
them.

There is a default daemon enabled of `gpg-agent`, but I prefer to manage the
daemon with `systemd --user`. Luckyly GnuPG comes with default files for
systemd, but they are not enabled. This module enables them.

The module also enables `gpg-agent` for SSH support. It is necessary to
specify the environment variable `SSH_AUTH_SOCK` to point to `gpg-agent`
socket. This line is already added in my custom `.bashrc` file:

 export SSH_AUTH_SOCK="/run/user/$(id -u)/gnupg/S.gpg-agent.ssh"

I use Xfce as desktop environment. There is only one problem: it autostarts
`ssh-agent`. I don't want it, so I kill it every time Xfce is started. This
line is already added in my custom `.bash_profile` file:

 pkill ssh-agent

This module also installs `pinentry-gtk`, because I don't like the default
installed that uses ncurses.

'''

=== lightdm

https://github.com/canonical/lightdm[LightDM] is a desktop manager easy to use,
flexible and lightweight. I use it simply because it is preinstalled with Fedora
Xfce spin.

I prefer an autologin method because the disk is encrypted and the computer have
only one user. I do not want to type two password when I boot the computer, and
the second is useless because if someone find the disk password he can grab the
data without problems. A display manager is also useless in my case because I
have only one user, but I keep it to have a "modern" desktop.

IMPORTANT: **DO NOT LOCK THE SCREEN**. If you lock the screen and go back to the
greeter, it crashes. I don't know why.

'''

=== xfwm4

This module installs my custom theme for Xfwm4. The theme has small borders and
it is really minimal. You can found more information on its
https://gitlab.com/ema-pe/backup-thinble-xfwm4-theme[repository].

'''

=== firefox

I use Mozilla Firefox as my main browser. I like it because is privacy focused,
fast and work really well in Linux. It is a big and complex software, it is not
easy to customize it.

==== Manual installation process

Unfortunately Firefox needs to be customized from GUI instead on CLI, so there
is not a real installer script. The steps to do are:

. From an active Firefox session, create a new profile with name
  `default-release` (default profile that comes with Fedora). You can access to
  the page via `about:profiles`.
. Switch to the new profile and delete the old one (if you want).
. Login to Firefox Sync (or download all extentions you want).
. Customize Firefox GUI.
. To set custom `user.js`, run my installer script.

==== Extentions

Extentions can't be installed from command line, so you need to install them
manually (or use https://www.mozilla.org/en-US/firefox/features/sync/[Firefox
Sync]). I use these extentions:

* https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/[*CanvasBlocker*]:
  prevent Canvas fingerprinting;
* https://addons.mozilla.org/en-US/firefox/addon/css-exfil-protection/[*CSS Exfil Protection*]:
  prevent CSS Exfil attacks;
* https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/[*Decentraleyes*]:
  local emulation of CDN;
* https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/[*HTTPS Everywhere*]:
  force HTTPS on sites;
* https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/[*Tridactyl*]:
  VIM keybindings on Firefox;
* https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/[*uBlock Origin*]:
  general AD blocker;
* https://addons.mozilla.org/en-US/firefox/addon/neat-url/[*Neat URL*]:
  remove garbage from URLs;
* https://addons.mozilla.org/en-US/firefox/addon/containerise/[*Containerise*]:
  automatically open websites in a container;
* https://github.com/evilpie/add-custom-search-engine[*Add custom search engine*]:
  add custom search engine.

All these extentions are automatically updated via Firefox, so you only need to
download them the first time.

==== Custom user.js

The `user.js` file is a file with all options to customize Firefox behaviour.
Many options can be selected from the graphical interface, but lots are hidden.

I use https://github.com/ghacksuserjs/ghacks-user.js[ghacks' `user.js`], an
`user.js` enhanced for privacy. I don't like some options, so I have also a
custom link:firefox/user.js[`user.js`] that overrides some options.

This module will download the latest version of ghacks' `user.js` and move that
file to the Firefox profile with suffix `default-release`. At the end it append
my custom options to `user.js` file on the profile.

== License

Every script is licensed under the link:LICENSE[MIT License].
