#!/usr/bin/env bash
#
# This script installs VLC on Fedora. See README.md for more informations.
#
# It is required "util.sh", my custom library for manage dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.me>. All
# right reserved. This file is licensed under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

ed_install_fusion "vlc"
