#!/usr/bin/env bash
#
# This script installs Pragha configuration.
#
# This script uses 'utils.sh', my custom library for manager dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.me>. All
# right reserved. This file is license under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

ed_exists "xdg-user-dir"
ed_exists "readlink"

dest_dir="$(xdg-user-dir)"

cp --verbose "$(readlink -f config)" "$dest_dir/.config/pragha/config"
ed_wlog "If you change settings from GUI the file will be overwritten!"
