#!/usr/bin/env bash
#
# This script installs my VIM configuration.
#
# This script uses 'utils.sh', my custom library for manager dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.me>. All
# right reserved. This file is license under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

ed_exists "xdg-user-dir"
ed_exists "readlink"

readonly vim_folder="$(xdg-user-dir)/.vim"

ed_make_dir "$vim_folder"

# vimrc.

ed_make_symlink "$(readlink -f vimrc)" "$vim_folder/vimrc"

# Color scheme.
ed_make_dir "$vim_folder/colors"

git submodule update --init papercolor-theme

ed_make_symlink "$(readlink -f papercolor-theme/colors/PaperColor.vim)" \
  "$vim_folder/colors/PaperColor.vim"

# Snippets.

ed_make_symlink "$(readlink -f snippets)" "$vim_folder"

# Plugins.

ed_make_dir "$vim_folder/pack"

git submodule update --init plugins/start/goyo.vim
git submodule update --init plugins/start/vim-pencil

ed_make_symlink "$(readlink -f plugins)" "$vim_folder/pack"
