#!/usr/bin/env bash

# This script sets up vim configuraion.

# Full path of this script.
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

XDG_USER_DIR="xdg-user-dir"

# Fallback if 'xdg-user-dir' isn't installed.
if [[ -z $(which "$XDG_USER_DIR") ]]; then
  USERDIR="$HOME"
else
  USERDIR="$( $XDG_USER_DIR )"
fi

# Vimrc settings.
VIMRC="$USERDIR/.vimrc"
if [[ -L "$VIMRC" ]]; then
  echo "vim: vimrc symlink already created!"
else
  ln --symbolic "$SCRIPTDIR/vimrc" "$VIMRC"
fi

# Color scheme settings.
git submodule update --init $SCRIPTDIR/papercolor-theme

COLOR_SCHEME="$USERDIR/.vim/colors/PaperColor.vim"
SRC_COLOR_SCHEME="$SCRIPTDIR/papercolor-theme/colors/PaperColor.vim"

if [[ -L "$COLOR_SCHEME" ]]; then
  echo "vim: color scheme (PaperColor.vim) symlink already created!"
else
  mkdir --parents "$USERDIR/.vim/colors/"

  ln --symbolic "$SRC_COLOR_SCHEME" "$COLOR_SCHEME"
fi

# Add snippets.
SRC_SNIPPETS="$SCRIPTDIR/snippets"
DST_SNIPPETS="$USERDIR/.vim/snippets"

if [[ ! -L "$DST_SNIPPETS" ]]; then
  mkdir --parent "$USERDIR/.vim"

  ln --symbolic "$SRC_SNIPPETS" "$DST_SNIPPETS"
else
  echo "vim: snippets directory is already created!"
fi
