#!/usr/bin/env bash
#
# This script installs and activate the icon pack. I use Papirus Dark.
#
# This script uses 'utils.sh', my custom library for manager dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.me>. All
# right reserved. This file is license under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

output="$(dnf list --installed papirus-icon-theme)"
installed=$?

if [[ $installed == "0" ]]; then
  ed_wlog "icon: Papirus icon packs are already installed!"
else
  ed_wlog "icon: root requested to install Papirus icon packs"

  sudo dnf install papirus-icon-theme
fi

# Update cache.
gtk-update-icon-cache "/usr/share/icons/Papirus-Dark"

# Activate Papirus Dark.
current="$(xfconf-query --channel xsettings --property /Net/IconThemeName)"
if [[ "$current" == "Papirus-Dark" ]]; then
  ed_wlog "icon: Papirus Dark icon pack already activated!"
else
  xfconf-query --channel xsettings --property /Net/IconThemeName --set Papirus-Dark
fi
