#!/usr/bin/env bash

# This script installs Gradle configuration file.

# Full path of this script.
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

USERDIR="$(xdg-user-dir)"

# Avoid to recreate the symlink.
GRADLE="$USERDIR/.gradle/gradle.properties"
if [[ -L "$GRADLE" ]]; then
  echo "gradle: gradle.properties symlink already created!"
else
  mkdir --parent "$USERDIR/.gradle"

  ln --symbolic --force "$SCRIPTDIR/gradle.properties" "$GRADLE"
fi
