#!/usr/bin/env bash
#
# This script installs git configurations.
#
# This script uses 'utils.sh', my custom library for manager dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.me>. All
# right reserved. This file is license under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

ed_exists "readlink"
ed_exists "dnf"

readonly dst_file="/etc/default/tlp"
readonly src_file="$(readlink -f tlp)"

# Install tlp via DNF.
install_tlp() {
  dnf list --installed tlp &>>/dev/null

  if [[ "$?" != "0" ]]; then
    ed_wlog "tlp: Root requested to install tlp"
    sudo dnf install --assumeyes tlp &>>/dev/null ||
      ed_elog "tlp: Failed to install tlp"
  fi
}

# Create a backup file with old configuration.
backup_old_conf() {
  if [[ "$(readlink -f $dst_file)" != "$src_file" ]]; then
    local bak_file="/etc/default/tlp.bak"

    ed_wlog "tlp: Root requested to create backup file"

    sudo cp --force "$dst_file" "$bak_file" &>>/dev/null ||
      ed_elog "tlp: Failed to create backup file!"

    ed_log "tlp: Backup file created : $bak_file"
  fi
}

# Apply tlp configuration.
apply_config() {
  ed_make_symlink "$src_file" "$dst_file" sudo
}

enable_tlp() {
  sudo tlp start &>>/dev/null || ed_elog "tlp: Failed to start tlp!"
}

install_tlp
backup_old_conf
apply_config
enable_tlp
