#!/usr/bin/env bash
#
# Bash completion for 'adoc2latex' script.
#
# Copyright (c) 2020 Emanuele Petriglia <inbox@emanuelepetriglia.com>
# All rights reserved. This file is licensed under the MIT license.

complete -G '*.adoc' adoc2latex
