#!/usr/bin/env bash
#
# Bash completion for 'adoc2latex' script.
#
# Copyright (c) 2020 Emanuele Petriglia <inbox@emanuelepetriglia.com>
# All rights reserved. This file is licensed under the MIT license.

_adoc2latex() {
  local current
  current="${COMP_WORDS[$COMP_CWORD]}"
  mapfile -t COMPREPLY < <(compgen -W "$(compgen -G '*.adoc')" -- "$current")
  return 0
}

complete -F _adoc2latex adoc2latex
