#!/usr/bin/env bash
#
# Bash completion for 'aenami' script.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.com>
# All rights reserved. This file is licensed under the MIT license.

_aenami() {
  local current previous options words
  COMPREPLY=()
  current="${COMP_WORDS[$COMP_CWORD]}"
  previous="${COMP_WORDS[$COMP_CWORD - 1]}"
  options="-h --help -d --directory -f --force"

  if [[ "$previous" == "-d" || "$previous" == "--directory" ]]; then
    words="$(compgen -A directory -- "$current")"
  else
    words="$options"
  fi

  COMPREPLY=( $(compgen -W "$words" -- "$current") )
  return 0
}

complete -F _aenami aenami
