#!/usr/bin/env bash
#
# Bash completion for 'musicconvert' script.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.com>
# All rights reserved. This file is licensed under the MIT license.

_musicconvert() {
  local current previous options words
  COMPREPLY=()
  current="${COMP_WORDS[$COMP_CWORD]}"
  previous="${COMP_WORDS[$COMP_CWORD - 1]}"
  options="-h --help -s --src -j --jobs"

  # It is a command.
  if [[ "$current" == -* ]]; then
    words="$options"
  else # It is an argument.
    case "$previous" in
      -j|--jobs) words="$(nproc)" ;;
      *)
        COMPREPLY="$(compgen -A directory -- "$current")"
        return 0
        ;;
    esac
  fi

  COMPREPLY=( $(compgen -W "$words" -- "$current") )
  return 0
}

complete -F _musicconvert musicconvert
