#!/usr/bin/env bash
#
# Bash completion for 'osmgpx' script.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.com>
# All rights reserved. This file is licensed under the MIT license.

_osmgpx() {
  local current options words
  COMPREPLY=()
  current="${COMP_WORDS[$COMP_CWORD]}"
  options="-h --help"

  if [[ "$current" == -* ]]; then
    words="$options"
  else # GPX files.
    words="$(compgen -A file -X '!*.gpx')"
  fi

  mapfile -t COMPREPLY < <(compgen -W "$words" -- "$current")
  return 0
}

complete -F _osmgpx osmgpx
