#!/usr/bin/env bash
#
# Bash completion for 'screen-off' script.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.com>
# All rights reserved. This file is licensed under the MIT license.

complete -W '-h --help' screen-off
