#!/usr/bin/env bash
#
# This script installs Docker on Debian. Root required. It follows the
# instructions located on Docker docs[0].
#
# I prefer to install Docker via APT repository.
#
# Copyright (c) 2018 Emanuele Petriglia <inbox@emanuelepetriglia.me>. This file
# is relased under the MIT license.
#
# [0]: https://docs.docker.com/install/linux/docker-ce/debian

DEBIAN_VERSION="$(lsb_release -cs)"

GPG_DEBIAN="https://download.docker.com/linux/debian/gpg"
GPG_DEBIAN_FINGERPRINT="9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88"

DOCKER_REPO_URL="https://download.docker.com/linux/debian"

APT="apt-get --quiet"

error() {
  echo "$@" >&2
  exit 1
}

echo-bold() {
  echo "$(tput bold)$1$(tput sgr0)"
}

# If Docker is already installed is not necessary to do run this script.
if [[ "$(dpkg --get-selections | grep -v deinstall | grep docker-ce)" ]]; then
  error "Docker is already installed."
fi

# Root is required because this script needs to run apt.
if [[ "$EUID" != 0 ]]; then
    error "Please run this script as root."
fi

# Part one: set up Docker's repository.
# -------------------------------------


# It is better to run "apt-get update" before any operation with apt.
echo-bold "$APT update"
$APT update
echo

# Necessary packages to install Docker's repository.
packages="apt-transport-https software-properties-common wget"

echo-bold "$APT install --no-install-recommends $packages"
$APT install --no-install-recommends --yes $packages
echo

# The GPG key used to verify packages. It must be checked manually.
echo-bold "wget --quiet --output-document=- $GPG_DEBIAN | apt-key add -"
wget --quiet --output-document=- $GPG_DEBIAN | apt-key add -
echo

echo-bold "Verifying GPG key..."
if [[ ! $(apt-key list 2>/dev/null | grep "$GPG_DEBIAN_FINGERPRINT") ]]; then
  error "No key found!"
fi

echo-bold "Correct!"
echo

# It is better to check if the repository is added to /etc/apt/sources.list
# previously, otherwise multiple runs of this script can pollute that file.
if [[ ! $(cat /etc/apt/sources.list | grep "$DOCKER_REPO_URL") ]]; then
  echo-bold "add-apt-repository \"deb [arch=amd64] $DOCKER_REPO_URL \
                  $DEBIAN_VERSION stable\""
  add-apt-repository "deb [arch=amd64] $DOCKER_REPO_URL $DEBIAN_VERSION stable"
else
  echo-bold "Docker repository is already added to /etc/apt/sources.list!"
fi
echo

# Part two: install and test Docker.
# ----------------------------------

echo-bold "$APT update"
$APT update
echo

echo-bold "$APT install --no-install-recommends --yes docker-ce"
$APT install --no-install-recommends --yes docker-ce
echo

echo-bold "docker run hello-world"
docker run hello-world
echo

# Part three: other commands related to Docker.
# ---------------------------------------------

# I prefer to disable Docker starting on boot up, I think it is better to start
# it only when needed.
echo-bold "systemctl disable docker"
systemctl disable docker
