#!/usr/bin/env bash
#
# This script installs LightDM configuration.
#
# This script uses 'utils.sh', my custom library for manager dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.me>. All
# right reserved. This file is license under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

ed_exists "readlink"

ed_make_symlink "$(readlink -f lightdm.conf)" "/usr/share/lightdm/lightdm.conf.d/70_start_xfce_session.conf" sudo
