#!/usr/bin/env bash
#
# This script activates Arc Dark GTK+ theme, that is preinstalled on Fedora 29.
#
# This script uses 'utils.sh', my custom library for manager dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.me>. All
# right reserved. This file is license under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

# Check if it is installed Arc theme.
output="$(dnf list --installed arc-theme)"
installed=$?

if [[ $installed == "0" ]]; then
  ed_wlog "gtk: Arc themes are already installed!"
else
  ed_wlog "gtk: root requested to install Arc themes"

  sudo dnf install arc-theme
fi

# Activate the theme.
current="$(xfconf-query --channel xsettings --property /Net/ThemeName)"
if [[ "$current" == "Arc-Dark" ]]; then
  ed_wlog "gtk: Arc Dark theme is already activated!"
else
  xfconf-query --channel xsettings --property /Net/IconThemeName --set Arc-Dark
fi
