#!/usr/bin/env bash
#
# This script install my Xfce configuration.
#
# This script uses 'utils.sh', my custom library for manager dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.com>. All
# right reserved. This file is license under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

ed_exists "xdg-user-dir"
ed_exists "readlink"

readonly dest_dir="$(xdg-user-dir)/.config/xfce4"

# Install xfce4-taskmanager configuration

ed_make_symlink "$(readlink -f xfce4-taskmanager.rc)" "$dest_dir/xfce4-taskmanager.rc"
ed_wlog "If you change a setting from GUI the link will be removed! FIX in the future"

# Install xfce4-termina configuration

ed_make_symlink "$(readlink -f terminal/terminalrc)" "$dest_dir/terminal/terminalrc"
ed_wlog "If you change a setting from GUI the link will be removed! FIX in the future"

ed_make_dir "$dest_dir/terminal/colorschemes"
ed_make_symlink "$(readlink -f terminal/dracula.theme)" \
  "$dest_dir/terminal/colorschemes/dracula.theme"
