#!/usr/bin/env bash
#
# This script installs GnuPG v2 configurations.
#
# This script uses 'utils.sh', my custom library for manager dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.me>. All
# right reserved. This file is license under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

ed_exists "xdg-user-dir"
ed_exists "readlink"

dest_dir="$(xdg-user-dir)/.gnupg"

ed_make_dir "$dest_dir"

ed_make_symlink "$(readlink -f gpg.conf)" "$dest_dir/gpg.conf"
ed_make_symlink "$(readlink -f gpg-agent.conf)" "$dest_dir/gpg-agent.conf"
ed_make_symlink "$(readlink -f sshcontrol)" "$dest_dir/sshcontrol"
