#!/usr/bin/env bash
#
# This script installs Thinble XFWM theme, my custom theme.
#
# This script uses 'utils.sh', my custom library for manager dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.me>. All
# right reserved. This file is license under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

ed_exists "xdg-user-dir"
ed_exists "readlink"

# Update or initialize the submodule.
git submodule update --init "thinble"

dest_dir="$(xdg-user-dir)/.local/share/themes"
ed_make_dir "$dest_dir"

ed_make_symlink "$(readlink -f thinble)" "$dest_dir/thinble"
