#!/usr/bin/env bash
#
# This script install custom 'user.js' file on my Firefox profile. The profile
# is located by te folder that ends with "default-release".
#
# This script uses 'util.sh', my custom library to manage dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.me>. All
# right reserved. This file is license under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

ed_exists "xdg-user-dir"
ed_exists "wget"

# Select only the profile with "default-release" suffix.
readonly firefox_profiles="$(xdg-user-dir)/.mozilla/firefox"
if [[ ! -d "$firefox_profiles" ]]; then
  ed_elog "No Firefox folder found. It is installed?"
fi

profile="$(ls $firefox_profiles -1 | grep default-release)"
if [[ ! "$profile" ]]; then
  ed_elog "No profile with suffix 'emanuele' found!"
fi
readonly profile="$firefox_profiles/$profile"

# Installs custom user.js
readonly ghacks_js_url="https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/user.js"
readonly ghacks_js="ghacks-user.js"
readonly emape_js="user.js"
readonly user_js="$profile/user.js"

wget --no-verbose --show-progress --output-document=ghacks-user.js \
  "$ghacks_js_url" || ed_elog "firefox: Failed to download ghacks-user.js!"

cat "$ghacks_js" > "$user_js"
cat "$emape_js" >> "$user_js"

rm --force "$ghacks_js"
