#!/usr/bin/env bash

# This script creates the symlink of Terminator configuration.

# Full path of this script.
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

USERDIR="$(xdg-user-dir)"

LN="ln --symbolic --force --verbose"

# Avoid to recreate the symlink.
TERMINATOR="$USERDIR/.config/terminator/config"
if [[ -L "$TERMINATOR" ]]; then
  echo "terminator: config symlink already created!"
else
  $LN "$SCRIPTDIR/config" "$TERMINATOR"
fi
