#!/usr/bin/env bash
#
# This script installs pass.
#
# This script uses 'utils.sh', my custom library for manager dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.me>. All
# right reserved. This file is license under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

# Check if it is installed Arc theme.
output="$(dnf list --installed pass)"
installed=$?

if [[ $installed == "0" ]]; then
  ed_wlog "pass: pass is already installed!"
else
  ed_wlog "pass: root requested to install pass"

  sudo dnf install arc-theme
fi
