#!/usr/bin/env bash
#
# This script installs youtube-dl.
#
# This script uses 'utils.sh', my custom library for manager dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.me>. All
# right reserved. This file is license under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

output="$(dnf list --installed youtube-dl)"
installed=$?

if [[ $installed == "0" ]]; then
  ed_wlog "youtube-dl: youtube-dl already installed!"
else
  ed_wlog "youtube-dl: root requested to install youtube-dl"

  sudo dnf install youtube-dl
fi
