#!/usr/bin/env bash
#
# This file is called only one time, when the environment is started.
#
# Copyright (c) Emanuele Petriglia <inbox@emanuelepetriglia.com> 2018-2019
# This file is lincensed under the MIT license.

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
  # shellcheck disable=SC1090
  . ~/.bashrc
fi

# Add home directory to PATH.
export PATH="$PATH:/home/emanuele/.local/bin"

# Because ssh-agent is automatically started by Xfce, and I don't know how to
# disable it.
pkill ssh-agent

# Disable Less' file history.
export LESSHISTFILE="-"
