#!/usr/bin/env bash
# My personal configuration of Bash. It contains my settings and some useful
# scripts that I use ofter.
#
# Copyright (c) Emanuele Petriglia <inbox@emanuelepetriglia.com> 2018
# This file is lincensed under the MIT license.
#
# This file is called every time a shell is started. It is also called by
# '.bash_profile' only once.

# Bash settings {{{

# Enable auto-completion feature.
if [[ -f "/etc/profile.d/bash_completion.sh" ]]; then
  # shellcheck disable=SC1091
  . /etc/profile.d/bash_completion.sh
fi

# }}}

# Global variables {{{

# Bash prompt.
export PS1="[\u@\h \[\e[36m\]\W\[\e[m\]]\\$ "

# Enable SSH support for gpg-agent.
export SSH_AUTH_SOCK="/run/user/$EUID/gnupg/S.gpg-agent.ssh"

# Default editor.
export EDITOR=vim

# }}}

# Small scripts {{{

# Prints the closest IPv4 and IPv6 DNS resolvers in the OpenNIC network.
opennic() {
  echo "Closest IPv4 (IP, name and reliability):"
  curl "https://api.opennic.org/geoip/?list&res=4&ipv=4"
  echo
  echo "Closest IPv6 (IP, name and reliability):"
  curl "https://api.opennic.org/geoip/?list&res=4&ipv=6"
  echo
}

# Colorized man pages.
# Thanks to: https://news.ycombinator.com/item?id=12304730
man() {
   LESS_TERMCAP_mb=$(printf "\e[1;31m") \
   LESS_TERMCAP_md=$(printf "\e[1;31m") \
   LESS_TERMCAP_me=$(printf "\e[0m") \
   LESS_TERMCAP_se=$(printf "\e[0m") \
   LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
   LESS_TERMCAP_ue=$(printf "\e[0m") \
   LESS_TERMCAP_us=$(printf "\e[1;32m") \
   command man "$@"
}

# This small script upload the current clipboard content to https://hastebin.com,
# then shows the URL and copy it to the clipboard (erasing the previous
# content).
#
# This script is useful with my xfce4-terminal configuration, that copy all text
# selected to clipboard.
#
# This script requires the following extra commands: curl, xclip.
haste() {
  local endpoint url response

  endpoint="https://hastebin.com/documents"

  if [[ "$(command -v curl)" && "$(command -v xclip)" ]] ; then
    response="$(curl --request POST --silent --data "$(xclip -o)" "$endpoint")"

    # shellcheck disable=SC2181
    if (( $? == 0 )) ; then
      url="$(echo "$response" \
        | awk --field-separator '"' '{ print "https://hastebin.com/"$4 }')"

      echo "$url"

      echo -n "$url" | xclip -selection clipboard \
        || echo "Failed to copy URL to clipboard"
    else
      echo "Failed to upload the clipboard to https://hastebin.com" >&2
    fi

  else
    echo "This script requires curl and xclip to run." >&2
  fi
}

# Prints to the standard output a list of dreams in a fixed format. The list is
# filename ordered. The format is: "FILENAME - FIRST LINE OF THE DREAM". Usually
# the first line of the dream is the title.
list-dreams() {
  for dream in *.md; do
    printf "%s\t- %s\n" "${dream##*/}" "$(head -n 1 "$dream")"
  done
}

# }}}

# Bash history {{{

# More human-readable format.
export HISTTIMEFORMAT="[%F %T] "

# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# }}}

# Aliases {{{

# It stops Bash to record commands in the current session.
alias forget="unset HISTFILE"

# It downloads videos and then extracts the audio.
alias music-dl='youtube-dl -x --audio-format vorbis'

# It replace spaces to underscore and convert the text in lowercase.
alias renamefull="rename 's/ /_/g' * && rename 'y/A-Z/a-z/' *"

alias py="python3"

# Show all available snippets for VIM.
alias snippets="ls \$HOME/.vim/snippets"
alias snips="snippets"

# Enable colors for varous commands.
alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias tree="tree -C"

# Enable ls aliases.
alias ll="ls -l"
alias la="ls -A"
alias l="ls -CF"

# Run VIM in writing mode (see my .vimrc for more informations).
alias writing="vim -c Writing"

alias ..="cd .."

# Alias for my dotfiles script manager.
alias dot="dotfiles"

# Download a website page ('-k': fix local links, '-p' download resources).
alias web-archive="wget -p -k"

# }}}

# vim:foldmethod=marker
