# .bash_profile
#
# Copyright (c) Emanuele Petriglia <inbox@emanuelepetriglia.com> 2018
# This file is lincensed under the MIT license.
#
# This file is called only one time, when the environment is started.

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# Add home directory to PATH.
export PATH="$PATH:/home/emanuele/.local/bin"

# Because ssh-agent is automatically started by Xfce, and I don't know how to
# disable it.
pkill ssh-agent
