# My personal configuration of Bash.

# Colorized man pages.
# Thanks to: https://news.ycombinator.com/item?id=12304730
man() {
  LESS_TERMCAP_mb=$(printf "\e[1;31m") \
   LESS_TERMCAP_md=$(printf "\e[1;31m") \
   LESS_TERMCAP_me=$(printf "\e[0m") \
   LESS_TERMCAP_se=$(printf "\e[0m") \
   LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
   LESS_TERMCAP_ue=$(printf "\e[0m") \
   LESS_TERMCAP_us=$(printf "\e[1;32m") \
   command man "$@"
}

# It downloads videos and then extracts the audio.
alias music='youtube-dl -x --audio-format vorbis --audio-quality 3'

# It download videos form YouTube at HD format (because my bandwith is limited).
alias yt='youtube-dl -f "best[height=720]"'

# It replace spaces to underscore and convert the text in lowercase.
alias renamefull="rename 's/ /_/g' * && rename 'y/A-Z/a-z/' *"

# Needed by ssh-add.
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

# Default editor
export EDITOR=vim

# Set VIM keybindings on Bash
set -o vi

# Set VIM keybindings for all programs
set editing-mode vi
set keymap vi

# Enable core dumping
ulimit -c 50

# Python alias
alias py="python3"

# Show all available snippets for VIM.
alias snippets="ls $HOME/.vim/snippets"
alias snips="snippets"

# Enable ls aliases.
alias ll="ls -l"
alias la="ls -A"
alias l="ls -CF"

# Change directory to HOME directory (same as "cd ~").
alias home="cd $HOME"
alias h="home"

# Alias for personal script that manages a systemd-nspawn container.
alias j="java-dev"
