#!/usr/bin/env bash
# vim:foldmethod=marker
# My personal configuration of Bash. It contains my settings and some useful
# scripts that I use ofter.
#
# Copyright (c) Emanuele Petriglia <inbox@emanuelepetriglia.me> 2018
# This file is lincensed under the MIT license.

# Bash settings {{{

# Set VIM keybindings on Bash
set -o vi

# Set VIM keybindings for all programs.
set editing-mode vi
set keymap vi

if [[ -f "/etc/profile.d/bash_completion.sh" ]]; then
  . /etc/profile.d/bash_completion.sh
fi

# }}}

# Global variables {{{

# Bash prompt.
export PS1="[\u@\h \[\e[36m\]\W\[\e[m\]]\\$ "

# Enable SSH support for gpg-agent.
export SSH_AUTH_SOCK="/run/user/$(id -u)/gnupg/S.gpg-agent.ssh"

# Default editor.
export EDITOR=vim

# }}}

# Small scripts {{{
# Here there are my custom script that I often use. They are small and simple to
# understand. More complex scripts are located separately on dedicated files.

# Cheat sheet for command line programs.
# It uses cht.sh to query command via wget. Example: `cheat echo` or `chaeat`.
cheat() {
  wget --quiet --output-document - cht.sh/$1
}

# Colorized man pages.
# Thanks to: https://news.ycombinator.com/item?id=12304730
man() {
  LESS_TERMCAP_mb=$(printf "\e[1;31m") \
   LESS_TERMCAP_md=$(printf "\e[1;31m") \
   LESS_TERMCAP_me=$(printf "\e[0m") \
   LESS_TERMCAP_se=$(printf "\e[0m") \
   LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
   LESS_TERMCAP_ue=$(printf "\e[0m") \
   LESS_TERMCAP_us=$(printf "\e[1;32m") \
   command man "$@"
}

# Prints to the standard output a list of dreams in a fixed format. The list is
# filename ordered. The format is: "FILENAME - FIRST LINE OF THE DREAM". Usually
# the first line of the dream is the title.
list-dreams() {
  for dream in *.md; do
    printf "%s\t- %s\n" "${dream##*/}" "$(head -n 1 "$dream")"
  done
}

# }}}

# Other settings {{{

# Bash history {{{
#
# I prefer an unlimited Bash history. This makes CRTL+r more useful.
# Thanks to: https://stackoverflow.com/a/19533853

# Note: you need to remove the lines "HISTSIZE=1000" and "HISTFILESIZE=2000"
# from your's '.bashrc' file.

# Undocumented feature which sets the size to "unlimited".
# http://stackoverflow.com/questions/9457233/unlimited-bash-history
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "

# Change the file location because certain bash sessions truncate .bash_history
# file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history

# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# }}}

# }}}

# Aliases {{{
#
# Here there are my custom aliases. Some aliases can call functions in this
# file.

# It stops Bash to record commands in the current session.
alias forget="unset HISTFILE"

# It downloads videos and then extracts the audio.
alias music-dl='youtube-dl -x --audio-format vorbis'

# It download videos form YouTube at HD format (because my bandwith is limited).
alias yt-dl='youtube-dl -f "best[height=720]"'

# It replace spaces to underscore and convert the text in lowercase.
alias renamefull="rename 's/ /_/g' * && rename 'y/A-Z/a-z/' *"

alias py="python3"

# Show all available snippets for VIM.
alias snippets="ls $HOME/.vim/snippets"
alias snips="snippets"

# Enable colors for varous commands.
alias ls="ls --color=auto"
alias grep="grep --color=auto"

# Enable ls aliases.
alias ll="ls -l"
alias la="ls -A"
alias l="ls -CF"

# Run VIM in writing mode (see my .vimrc for more informations).
alias writing="vim -c Writing"

alias ..="cd .."

alias clr="clear"

alias tree="tree -C"

# }}}
