# vim:foldmethod=marker
# My personal configuration of Bash. It contains my settings and some useful
# scripts that I use ofter.
#
# Copyright (c) Emanuele Petriglia <inbox@emanuelepetriglia.me> 2018
# This file is lincensed under the MIT license.

# Bash settings {{{

# Set VIM keybindings on Bash
set -o vi

# Set VIM keybindings for all programs.
set editing-mode vi
set keymap vi

# }}}

# Global variables {{{

# Add custom PATH if necessary.
if [[ ! "$PATH" =~ "/home/$USER/.local/bin" ]]; then
  export PATH="$HOME/.local/bin:$PATH"
fi

# Needed by ssh-add.
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

# Default editor
export EDITOR=vim

# }}}

# Small scripts {{{
# Here there are my custom script that I often use. They are small and simple to
# understand. More complex scripts are located separately on dedicated files.

# Colorized man pages.
# Thanks to: https://news.ycombinator.com/item?id=12304730
man() {
  LESS_TERMCAP_mb=$(printf "\e[1;31m") \
   LESS_TERMCAP_md=$(printf "\e[1;31m") \
   LESS_TERMCAP_me=$(printf "\e[0m") \
   LESS_TERMCAP_se=$(printf "\e[0m") \
   LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
   LESS_TERMCAP_ue=$(printf "\e[0m") \
   LESS_TERMCAP_us=$(printf "\e[1;32m") \
   command man "$@"
}

# Convert a JPEG image to PNG and delete the original one. The JPEG image must
# ends with '.jpg' or '.jpeg'.
# It is required ImageMagick to convert images.
jpeg-to-png() {
  local JPEG="$1"

  if [[ ! -z "$JPEG" ]]; then
    local PNG="${JPEG/%.jp*g/.png}"

    convert $JPEG $PNG
    rm $JPEG
  else
    echo "Missing JPEG source image to convert!"
  fi
}

# Prints to the standard output a list of dreams in a fixed format. The list is
# filename ordered. The format is: "FILENAME - FIRST LINE OF THE DREAM". Usually
# the first line of the dream is the title.
list-dreams() {
  for dream in *.md; do
    printf "%s\t- %s\n" "${dream##*/}" "$(head -n 1 $dream)"
  done
}

# This commands allows you to change directory via shortcuts. You can see a list
# of available shortcuts with `jump list`.
# TODO: create a dedicated script.
jump() {
  local dest="$1"

  if [[ -z "$dest" ]]; then
    echo "error: you must give an argument"
  else
    case "$dest" in
      list)
        echo "nano -> ~/Documents/writing/novels/nanowrimo-2018"
        echo "writing -> ~/Documents/writing"
        ;;
      nano)
        cd ~/Documents/writing/novels/nanowrimo-2018
        ;;
      writing)
        cd ~/Documents/writing
        ;;
      *)
        echo "error: $dest is not a shortcut"
        ;;
    esac
  fi
}

# }}}

# Other settings {{{

# Starts gpg-agent ONLY if there is not a GUI enviroment (for example on a
# server or container). In the main host with a GUI gpg-agent is started
# automatically.
if [[ -z "$(dpkg -l | grep xserver)" && -z "$(pidof gpg-agent)" ]]; then
  eval $(gpg-agent --daemon)
fi

# Bash history {{{
#
# I prefer an unlimited Bash history. This makes CRTL+r more useful.
# Thanks to: https://stackoverflow.com/a/19533853

# Note: you need to remove the lines "HISTSIZE=1000" and "HISTFILESIZE=2000"
# from your's '.bashrc' file.

# Undocumented feature which sets the size to "unlimited".
# http://stackoverflow.com/questions/9457233/unlimited-bash-history
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "

# Change the file location because certain bash sessions truncate .bash_history
# file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history

# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# }}}

# }}}

# Aliases {{{
#
# Here there are my custom aliases. Some aliases can call functions in this
# file.

# It stops Bash to record commands in the current session.
alias forget="unset HISTFILE"

# It downloads videos and then extracts the audio.
alias music-dl='youtube-dl -x --audio-format vorbis'

# It download videos form YouTube at HD format (because my bandwith is limited).
alias yt-dl='youtube-dl -f "best[height=720]"'

# It replace spaces to underscore and convert the text in lowercase.
alias renamefull="rename 's/ /_/g' * && rename 'y/A-Z/a-z/' *"

# Python alias
alias py="python3"

# Show all available snippets for VIM.
alias snippets="ls $HOME/.vim/snippets"
alias snips="snippets"

# Enable ls aliases.
alias ll="ls -l"
alias la="ls -A"
alias l="ls -CF"

# Don't use less, instead use view (readonly file opened with vim).
alias less="view"

# Allows to create a Java application project with Gradle using a modern
# version.
alias java-setup="gradle wrapper --gradle-version 4.6; ./gradlew init --type java-application"

# Allows to see why a package is installed (using APT).
alias why="apt-cache rdepends --installed"

# Shows all installed packages on the system (using APT).
alias installed="apt list --installed"

# Converts a single JPEG image to PNG and delete the first one.
alias jtp="jpeg-to-png"

# Run VIM in writing mode (see my .vimrc for more informations).
alias writing="vim -c Writing"

# }}}
