#!/usr/bin/env bash
#
# This script installs my Bash configuration.
#
# This script uses 'utils.sh', my custom library for manager dotfiles.
#
# Copyright (c) 2019 Emanuele Petriglia <inbox@emanuelepetriglia.me>. All
# right reserved. This file is license under the MIT license. See LICENSE for
# more informations.

. ../.common/utils.sh

ed_exists "xdg-user-dir"
ed_exists "readlink"

readonly dst_dir="$(xdg-user-dir)"

ed_make_symlink "$(readlink -f bashrc)" "$dst_dir/.bashrc"
ed_make_symlink "$(readlink -f bash_profile)" "$dst_dir/.bash_profile"
